package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.OracleDB;
import java.sql.Statement;


public class MemberPermission {
 
    public static void createTable() {


        try (Connection conn = OracleDB.getConnection()) {

            //verification si la table existe
            String sql1 = "SELECT table_name FROM USER_TABLES WHERE table_name='MEMBERPERMISSION'";

            PreparedStatement stmt1 = conn.prepareStatement(sql1) ;
            ResultSet rs = stmt1.executeQuery() ;

            if (!rs.next()){

                //creation du table
                String sql2 = """
                    CREATE TABLE MEMBERPERMISSION (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        projectId NUMBER REFERENCES PROJECT(id),
                        memberId NUMBER REFERENCES USERS(id),
                        permissionId NUMBER REFERENCES PERMISSION(id)
                    )
                """;


                Statement stmt2 = conn.createStatement();
                stmt2.executeUpdate(sql2);

                System.out.println("Table MEMBERPERMISSION créée avec succès !");

                
            } else {

                System.out.println("La table 'MEMBERPERMISSION' existe déjà.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'MEMBERPERMISSION': " + e.getMessage());
        }
    }


}
