package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import database.OracleDB;

public class Notification {
    
    public static void createTable(){
        try(Connection conn = OracleDB.getConnection()){

            //table existe ?
            String sql1 = "SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME='NOTIFICATION'" ;
            PreparedStatement stmt1 = conn.prepareStatement(sql1) ;
            ResultSet rs = stmt1.executeQuery() ;

            if(!rs.next()){

                String sql2 = """
                        CREATE TABLE NOTIFICATION (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        projectId NUMBER REFERENCES PROJECT(id),
                        senderId NUMBER REFERENCES USERS(id),
                        receiverId NUMBER REFERENCES USERS(id),
                        isRead NUMBER(1) DEFAULT 0 CHECK (isRead IN (0,1)),
                        createdAt DATE DEFAULT SYSDATE
                        )
                        """; 

                Statement stmt = conn.createStatement() ;
                stmt.executeUpdate(sql2) ;

                System.out.println("Table NOTIFICATION créée avec succès !");

            } else {

                System.out.println("La table 'NOTIFICATION' existe déjà.");
            }

        }catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'NOTIFICATION': " + e.getMessage());
        }

        
    }
}
