package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.OracleDB;
import java.sql.Statement;


public class Permission {
 
    public static void createTable() {


        try (Connection conn = OracleDB.getConnection()) {

            //verification si la table existe
            String sql1 = "SELECT table_name FROM USER_TABLES WHERE table_name='PERMISSION'";

            PreparedStatement stmt1 = conn.prepareStatement(sql1) ;
            ResultSet rs = stmt1.executeQuery() ;

            if (!rs.next()){

                //creation du table
                String sql2 = """
                    CREATE TABLE PERMISSION (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(30) ,
                        description VARCHAR2(100)
                    )
                """;


                Statement stmt2 = conn.createStatement();
                stmt2.executeUpdate(sql2);

                System.out.println("Table PERMISSION créée avec succès !");

                
            } else {

                System.out.println("La table 'PERMISSION' existe déjà.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'PERMISSION': " + e.getMessage());
        }
    }


}
