package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;

import database.OracleDB;

public class Project {


    public static void createTable(){
        
        try(Connection conn = OracleDB.getConnection()){
            //table project existes ?
            String sql1 = "SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME='PROJECT' " ;
            PreparedStatement stmt1 = conn.prepareStatement(sql1) ;
            ResultSet rs = stmt1.executeQuery() ;

            if(!rs.next()){

                String sql2 = """
                        CREATE TABLE PROJECT(
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        name VARCHAR2(20) ,
                        createdBy NUMBER REFERENCES USERS(id),
                        description VARCHAR2(100),
                        code VARCHAR2(50),
                        status VARCHAR2(10) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','ARCHIVED','COMPLETED')) ,
                        createdAt DATE DEFAULT SYSDATE ,
                        updatedAt DATE DEFAULT SYSDATE ,
                        endDate DATE 
                        )
                        """;
                PreparedStatement stmt2 = conn.prepareStatement(sql2) ;
                stmt2.executeUpdate() ;

                System.out.println("Table PROJECT créée avec succès !");

            }else{
                 System.out.println("La table 'PROJECT' existe déjà.");

            }

        }catch(SQLException e){
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'PROJECT': " + e.getMessage());

        }
    }
    
    public static boolean create(String name,int createdBy,String descrition,String code,Date endDate){
        try(Connection conn = OracleDB.getConnection()){

            String sql =  """
                          INSERT INTO PROJECT(name,createdBy,description,code,endDate)
                            VALUES (?,?,?,?,?)
                        """;

            PreparedStatement stmt = conn.prepareStatement(sql) ;
            stmt.setString(1,name);
            stmt.setInt(2,createdBy);
            stmt.setString(3,descrition);
            stmt.setString(4,code);
            stmt.setDate(5,endDate);

            int rows = stmt.executeUpdate();

            if (rows > 0) {
                System.out.println("Projet créé avec succès !");
                return true;
            } else {
                System.out.println("Aucun projet n'a été inséré.");
                return false;
            }

        }catch(SQLException e){
            e.printStackTrace();
            System.out.println("erreur lors l'ajout de projet");
            return false ;
        }
        
    }
}
