package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import database.OracleDB;

public class TaskTable {

    public static void createTable() {
        try (Connection conn = OracleDB.getConnection()) {
            // Vérification si la table existe
            String sql1 = "SELECT table_name FROM USER_TABLES WHERE table_name='TASK'";
            PreparedStatement stmt1 = conn.prepareStatement(sql1);
            ResultSet rs = stmt1.executeQuery();

            if (!rs.next()) {
                // Création de la table
                String sql2 = """
                    CREATE TABLE TASK (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        projectId NUMBER REFERENCES PROJECT(id),
                        memberId NUMBER REFERENCES USERS(id),
                        title VARCHAR2(20),
                        description VARCHAR2(100),
                        status VARCHAR2(10) CHECK (status IN ('ToDo','InProgress','Done','Canceled')),
                        priority NUMBER CHECK (priority IN (0,1,2,3,4,5)),
                        createdAt DATE DEFAULT SYSDATE,
                        updatedAt DATE 
                    )
                """;

                Statement stmt2 = conn.createStatement();
                stmt2.executeUpdate(sql2);
                System.out.println("Table TASK créée avec succès !");
            } else {
                System.out.println("La table 'TASK' existe déjà.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'TASK': " + e.getMessage());
        }
    }

    public static boolean create(int projectId, String title, String description, String status, int priority) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = """
                INSERT INTO TASK(projectId, title, description, status, priority)
                VALUES (?, ?, ?, ?, ?)
            """;

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, projectId);
            stmt.setString(2, title);
            stmt.setString(3, description);
            stmt.setString(4, status);
            stmt.setInt(5, priority);

            int rows = stmt.executeUpdate();
            if (rows > 0) {
                System.out.println("Tâche créée avec succès !");
                return true;
            } else {
                System.out.println("Aucune tâche n'a été insérée.");
                return false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de l'ajout de la tâche");
            return false;
        }
    }

    public static boolean update(int id, String title, String description, String status, int priority) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = """
                UPDATE TASK 
                SET title = ?, description = ?, status = ?, priority = ?, updatedAt = SYSDATE
                WHERE id = ?
            """;

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, title);
            stmt.setString(2, description);
            stmt.setString(3, status);
            stmt.setInt(4, priority);
            stmt.setInt(5, id);

            int rows = stmt.executeUpdate();
            if (rows > 0) {
                System.out.println("Tâche mise à jour avec succès !");
                return true;
            } else {
                System.out.println("Aucune tâche n'a été mise à jour.");
                return false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la mise à jour de la tâche");
            return false;
        }
    }

    public static boolean updateStatus(int id, String status) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = "UPDATE TASK SET status = ?, updatedAt = SYSDATE WHERE id = ?";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, status);
            stmt.setInt(2, id);

            int rows = stmt.executeUpdate();
            if (rows > 0) {
                System.out.println("Statut de la tâche mis à jour avec succès !");
                return true;
            } else {
                System.out.println("Aucune tâche n'a été mise à jour.");
                return false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la mise à jour du statut");
            return false;
        }
    }

    public static boolean delete(int id) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = "DELETE FROM TASK WHERE id = ?";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, id);

            int rows = stmt.executeUpdate();
            if (rows > 0) {
                System.out.println("Tâche supprimée avec succès !");
                return true;
            } else {
                System.out.println("Aucune tâche n'a été supprimée.");
                return false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la suppression de la tâche");
            return false;
        }
    }

    public static ResultSet getAll() {
        try {
            Connection conn = OracleDB.getConnection();
            String sql = "SELECT * FROM TASK ORDER BY createdAt DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            return stmt.executeQuery();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la récupération des tâches");
            return null;
        }
    }

    public static ResultSet getById(int id) {
        try {
            Connection conn = OracleDB.getConnection();
            String sql = "SELECT * FROM TASK WHERE id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, id);
            return stmt.executeQuery();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la récupération de la tâche");
            return null;
        }
    }

    public static ResultSet getByProject(int projectId) {
        try {
            Connection conn = OracleDB.getConnection();
            String sql = "SELECT * FROM TASK WHERE projectId = ? ORDER BY createdAt DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, projectId);
            return stmt.executeQuery();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la récupération des tâches du projet");
            return null;
        }
    }

    public static ResultSet getByStatus(String status) {
        try {
            Connection conn = OracleDB.getConnection();
            String sql = "SELECT * FROM TASK WHERE status = ? ORDER BY createdAt DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, status);
            return stmt.executeQuery();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors de la récupération des tâches par statut");
            return null;
        }
    }

    public static int count() {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = "SELECT COUNT(*) as total FROM TASK";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getInt("total");
            }
            return 0;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors du comptage des tâches");
            return 0;
        }
    }

    public static int countByStatus(String status) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = "SELECT COUNT(*) as total FROM TASK WHERE status = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, status);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getInt("total");
            }
            return 0;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors du comptage des tâches par statut");
            return 0;
        }
    }

    public static int countByProject(int projectId) {
        try (Connection conn = OracleDB.getConnection()) {
            String sql = "SELECT COUNT(*) as total FROM TASK WHERE projectId = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, projectId);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getInt("total");
            }
            return 0;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erreur lors du comptage des tâches du projet");
            return 0;
        }
    }
}