package database.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.OracleDB;
import java.sql.Statement;

import models.User;


public class UserTable {
 
    public static void createTable() {


        try (Connection conn = OracleDB.getConnection()) {

            //verification si la table existe
            String sql1 = "SELECT table_name FROM USER_TABLES WHERE table_name='USERS'";

            PreparedStatement stmt1 = conn.prepareStatement(sql1) ;
            ResultSet rs = stmt1.executeQuery() ;

            if (!rs.next()){

                //creation du table
                String sql2 = """
                    CREATE TABLE USERS (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        firstName VARCHAR2(50),
                        lastName VARCHAR2(50),
                        email VARCHAR2(100) UNIQUE,
                        profession VARCHAR2(40),
                        password VARCHAR2(100),
                        phone VARCHAR2(20),
                        connectedAt DATE,
                        status VARCHAR2(10) CHECK (status IN ('ON','OFF')),
                        profilePic VARCHAR2(200),
                        createdAt DATE DEFAULT SYSDATE
                    )
                """;


                Statement stmt2 = conn.createStatement();
                stmt2.executeUpdate(sql2);

                System.out.println("Table USERS créée avec succès !");

                
            } else {

                System.out.println("La table 'USERS' existe déjà.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Erreur lors de la création de la table 'USERS': " + e.getMessage());
        }
    }


    public static boolean create(String firstName, String lastName, String email,String profession, String phone,String profilePic, String password) {

        String sql = "INSERT INTO USERS (firstName, lastName, email,profession,phone,profilePic,password, status, createdAt) " +
                 "VALUES (?, ?, ?, ?, ?, ?, ?, 'OFF', SYSDATE)";

        try (Connection conn = OracleDB.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, firstName);
            stmt.setString(2, lastName);
            stmt.setString(3, email);
            stmt.setString(4, profession);
            stmt.setString(5, phone);
            stmt.setString(6, profilePic);
            stmt.setString(7, password);

            stmt.executeUpdate();

            System.out.println("Utilisateur créé avec succès !");
            return true ;

        } catch (SQLException e) {
            e.printStackTrace();
            return false ;
        }
    }


    public static User login(String email,String password){

        String sql = """
                    SELECT id,firstName,lastName,email,profession,phone,profilePic
                    FROM USERS
                    WHERE email = ? AND password = ?
                    """ ;

        try (Connection conn = OracleDB.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, email);
            stmt.setString(2, password);

            // Exécuter la requête
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                int id = rs.getInt("id") ;
                String firstName = rs.getString("firstName");
                String lastName = rs.getString("lastName");
                String profession = rs.getString("profession") ;
                String phone = rs.getString("phone") ;
                String profilePic = rs.getString("profilePic") ;

                return new User(id,firstName,lastName,email,phone,profession,profilePic) ;
            }

            return null ;

        } catch (SQLException e) {
            e.printStackTrace();
            return null ;
        }
 
    }

}
